server:
  port: 8080
    
spring:
  datasource:
    url: "jdbc:mysql://ee417.crxkzf89o3fh.eu-west-1.rds.amazonaws.com/cyber_cafe1"
    username: "EE417"
    password: "2023_EE417"
#    url: "jdbc:mysql://127.0.0.1:3306/cyber_cafe1"
#    username: "root"
#    password: "offaly903"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      platform: mysql

logging:
  level:
    org:
      springframework:
        security: DEBUG